require('marcantondahmen.plugins-setup')

require('marcantondahmen.core.options')
-- require('marcantondahmen.core.colorschemes.nord')
require('marcantondahmen.core.colorschemes.tokyonight')
require('marcantondahmen.core.keymaps')

require('marcantondahmen.plugins.lsp.conform')
require('marcantondahmen.plugins.lsp.lsp-signature')
require('marcantondahmen.plugins.lsp.lspsaga')
require('marcantondahmen.plugins.lsp.mason')
require('marcantondahmen.plugins.lsp.nvim-lsp-file-operations')
require('marcantondahmen.plugins.lsp.nvim-lspconfig')

require('marcantondahmen.plugins.alpha-nvim')
require('marcantondahmen.plugins.auto-session')
require('marcantondahmen.plugins.autopairs')
require('marcantondahmen.plugins.barbar')
require('marcantondahmen.plugins.barbecue')
require('marcantondahmen.plugins.comment')
require('marcantondahmen.plugins.diffview')
require('marcantondahmen.plugins.gitsigns')
require('marcantondahmen.plugins.indent-blankline')
require('marcantondahmen.plugins.lualine')
require('marcantondahmen.plugins.luasnip')
require('marcantondahmen.plugins.navbuddy')
require('marcantondahmen.plugins.neogen')
require('marcantondahmen.plugins.nvim-cmp')
require('marcantondahmen.plugins.nvim-highlight-colors')
require('marcantondahmen.plugins.nvim-notify')
require('marcantondahmen.plugins.nvim-spectre')
require('marcantondahmen.plugins.nvim-tmux-navigation')
require('marcantondahmen.plugins.nvim-tree')
require('marcantondahmen.plugins.nvim-web-devicons')
require('marcantondahmen.plugins.tagalong')
require('marcantondahmen.plugins.telescope')
require('marcantondahmen.plugins.toggleterm')
require('marcantondahmen.plugins.treesitter')
require('marcantondahmen.plugins.trouble')
require('marcantondahmen.plugins.vim-maximizer')
require('marcantondahmen.plugins.vim-pencil')

require('marcantondahmen.self-update')
