require('marcantondahmen.plugins-setup')
require('marcantondahmen.core.options')

-- require('marcantondahmen.core.colorschemes.nord')
require('marcantondahmen.core.colorschemes.tokyonight')

require('marcantondahmen.core.keymaps')
require('marcantondahmen.plugins.tmux-navigation')
require('marcantondahmen.plugins.devicons')
require('marcantondahmen.plugins.comment')
require('marcantondahmen.plugins.nvim-tree')
require('marcantondahmen.plugins.lualine')
require('marcantondahmen.plugins.telescope')
require('marcantondahmen.plugins.nvim-cmp')
require('marcantondahmen.plugins.lsp.mason')
require('marcantondahmen.plugins.lsp.lspconfig')
require('marcantondahmen.plugins.lsp.lspsaga')
require('marcantondahmen.plugins.lsp.lsp-signature')
require('marcantondahmen.plugins.lsp.lsp-file-operations')
require('marcantondahmen.plugins.lsp.conform')
require('marcantondahmen.plugins.treesitter')
require('marcantondahmen.plugins.autopairs')
require('marcantondahmen.plugins.gitsigns')
require('marcantondahmen.plugins.diffview')
require('marcantondahmen.plugins.alpha')
require('marcantondahmen.plugins.trouble')
require('marcantondahmen.plugins.barbar')
require('marcantondahmen.plugins.toggleterm')
require('marcantondahmen.plugins.notify')
require('marcantondahmen.plugins.navbuddy')
require('marcantondahmen.plugins.neogen')
require('marcantondahmen.plugins.maximizer')
require('marcantondahmen.plugins.luasnip')
require('marcantondahmen.plugins.tagalong')
require('marcantondahmen.plugins.highlight-colors')
require('marcantondahmen.plugins.indent-blankline')
require('marcantondahmen.plugins.barbecue')
require('marcantondahmen.plugins.spectre')
require('marcantondahmen.plugins.auto-session')
require('marcantondahmen.plugins.vim-pencil')

require('marcantondahmen.self-update')
